In [8]:
import numpy as np
import scipy

In [9]:
def bcirc(A,B):
    m_1,n_1 = np.shape(A)
    if m_1 !=n_1:
        print("err")
    m_2,n_2 = np.shape(B)
    if m_2 != n_2 or m_2 !=m_1:
        print("err")
    C = np.zeros((2*m_1,2*m_1))
    C[:m_1,:m_1]=A
    C[:m_1,m_1:2*m_1] = B
    C[m_1:2*m_1,:m_1]=B
    C[m_1:2*m_1,m_1:2*m_1] = A
    return C

In [10]:
A = np.array([[1,3],[1,-5]])
B = np.array([[2,3],[2,14]])

In [11]:
C = bcirc(A,B)

In [12]:
print(C)

[[ 1.  3.  2.  3.]
 [ 1. -5.  2. 14.]
 [ 2.  3.  1.  3.]
 [ 2. 14.  1. -5.]]


In [13]:
from scipy.linalg import svdvals

In [14]:
#Singular Values of A
scipy.linalg.svdvals(A.astype(float))

array([5.84161925, 1.3694833 ])

In [15]:
#Singular Values of B
scipy.linalg.svdvals(B.astype(float))

array([14.51560977,  1.51560977])

In [16]:
#Singular Values of A+B
scipy.linalg.svdvals(A.astype(float)+B.astype(float))

array([11.59298535,  0.77633153])

In [17]:
#Singular Values of A-B
scipy.linalg.svdvals(A.astype(float)-B.astype(float))

array([19.02637039,  0.99861401])

In [18]:
#Singular Values of bcirc([A,B])
scipy.linalg.svdvals(C.astype(float))

array([19.02637039, 11.59298535,  0.99861401,  0.77633153])

In [174]:
def bcirc(A,B,D):
    m_1,n_1 = np.shape(A)
    if m_1 !=n_1:
        print("err")
    m_2,n_2 = np.shape(B)
    if m_2 != n_2 or m_2 !=m_1:
        print("err")
    m_3,n_3 = np.shape(D)
    if m_3 != n_3 or m_3 !=m_1:
        print("err")
    C = np.zeros((3*m_1,3*m_1))
    C[:m_1,:m_1]=A
    C[:m_1,m_1:2*m_1] = B
    C[:m_1,2*m_1:3*m_1] = D
    C[m_1:2*m_1,:m_1]=B
    C[m_1:2*m_1,m_1:2*m_1] = D
    C[m_1:2*m_1,2*m_1:3*m_1] = A
    C[2*m_1:3*m_1,:m_1]=D
    C[2*m_1:3*m_1,m_1:2*m_1] = A
    C[2*m_1:3*m_1,2*m_1:3*m_1] = B
    return C

In [220]:
A = np.array([[1,3,4],[2,5,6],[3,4,6]])
B = np.array([[2,5,5],[-2,14,2],[5,7,4]])
D = np.array([[4,3,3],[5,10,3],[-2,-3,-5]])

In [221]:
C_2 = bcirc(A,B,D)

In [222]:
scipy.linalg.svdvals(C_2.astype(float))

array([36.77715412, 15.26091393, 15.26091393, 10.47153186, 10.47153186,
        8.19214096,  2.5159017 ,  1.85782848,  1.85782848])

In [223]:
scipy.linalg.svdvals(A.astype(float)+B.astype(float)+D.astype(float))

array([36.77715412,  8.19214096,  2.5159017 ])

In [224]:
scipy.linalg.svdvals(-A.astype(float)+B.astype(float)-D.astype(float))

array([13.49059837,  4.89336406,  0.24237133])

In [225]:
scipy.linalg.svdvals(A.astype(float)-B.astype(float)-D.astype(float))

array([19.78212877,  8.52762902,  3.73455815])

In [226]:
scipy.linalg.svdvals(A.astype(float)+B.astype(float)-D.astype(float))

array([24.95905815,  9.38781742,  1.70713224])

In [177]:
A = np.array([[1,3],[2,-5]])
B = np.array([[2,-5],[2,-14]])
D = np.array([[4,3],[-5,-10]])

In [178]:
C_2 = bcirc(A,B,D)

In [179]:
scipy.linalg.svdvals(C_2.astype(float))

array([29.04536102, 11.80506215, 11.80506215,  6.95463898,  6.45294565,
        6.45294565])

In [180]:
scipy.linalg.svdvals(A.astype(float)+B.astype(float)+D.astype(float))

array([29.04536102,  6.95463898])

In [231]:
A = np.array([[1,3,4],[2,5,6],[3,4,6]])
B = np.array([[2,5,5],[2,14,2],[5,7,4]])
D = np.array([[4,3,3],[5,10,3],[-2,-3,-5]])

In [232]:
C_2 = bcirc(A,B,D)

In [233]:
scipy.linalg.svdvals(C_2.astype(float))

array([37.75809848, 15.48375768, 15.48375768,  8.5165155 ,  8.5165155 ,
        7.17791923,  2.39211449,  2.39211449,  2.19168312])

In [234]:
scipy.linalg.svdvals(A.astype(float)+B.astype(float)+D.astype(float))

array([37.75809848,  7.17791923,  2.19168312])

In [235]:
scipy.linalg.svdvals(-A.astype(float)+B.astype(float)-D.astype(float))

array([11.3315783 ,  4.53560051,  1.01176149])

In [236]:
scipy.linalg.svdvals(A.astype(float)-B.astype(float)-D.astype(float))

array([20.60439784,  8.32451718,  2.85678199])

In [226]:
scipy.linalg.svdvals(A.astype(float)+B.astype(float)-D.astype(float))

array([24.95905815,  9.38781742,  1.70713224])